[package]
name = "nemembory-server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
thiserror = "2.0.12"
async-trait = "0.1.89"
nemembory-core = { path = "D:\\git_repos\\nemembory\\nemembory-core" }
axum = { version = "0.8.7", features = ["ws"] }
tokio = { version = "1.48.0", features = ["full"] }
tracing-subscriber = "0.3.20"
